name: platform_specific_test
description: Platform specific code test.
version: 0.0.1
repository: https://github.com/MatijaNovosel/flutter-platform-specific-test
homepage: https://github.com/MatijaNovosel/flutter-platform-specific-test
environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.3.0"
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.testing
        pluginClass: TestingPlugin
      ios:
        pluginClass: TestingPlugin
